### ISSUE TITLE
Uncaught Error: Trying to send an unexpected type of value through port `fileUpdated`:Expecting ...

### ISSUE THREAD

**Issue by dholtz** [mbylstra/atom-elm-navigator#13]
After updating to the latest version(s), open any file and start typing.  

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [elm-navigator](https://github.com/mbylstra/atom-elm-navigator) package 1.1.4

### Stack Trace

Uncaught Error: Trying to send an unexpected type of value through port `fileUpdated`:
Expecting a String at _.filePath but instead got: undefined

```
At /Users/holtzhdm/.atom/packages/elm-navigator/elm/built/elm.js:3875

Error: Trying to send an unexpected type of value through port `fileUpdated`:
Expecting a String at _.filePath but instead got: undefined
    at Object.send (/packages/elm-navigator/elm/built/elm.js:3875:10)
    at /packages/elm-navigator/lib/elm-navigator.js:87:37
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-polymer 0.13.0 
busy-signal 1.3.0 
elm-format 2.1.0 
elm-instant 2.0.0 
elm-navigator 1.1.4 
elmjutsu 5.5.1 
git-plus 7.3.3 
html-to-elm 0.2.0 
intentions 1.1.2 
language-elm 1.5.0 
linter 2.1.2 
linter-elm-make 0.23.2 
linter-eslint 8.1.4 
linter-ui-default 1.2.2 
open-in-browser 0.4.7 
polymer-ide 0.3.0 
qolor 0.4.1 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by mbylstra** [comment]
Thanks for the report. This should be fixed in the latest version (1.1.6)
